FROM duluca/minimal-node-build-env

# project variables
ENV SRC_DIR /usr/src
ENV GIT_REPO https://github.com/josephhill1/lemon-mart.git
ENV SRC_CODE_LOCATION .
ENV BUILD_SCRIPT build:prod

# get source code
RUN mkdir -p $SRC_DIR
WORKDIR $SRC_DIR
# if necessary, do SSH setup here or copy source code from local or CI environment
RUN git clone $GIT_REPO .
# COPY $SRC_CODE_LOCATION .

RUN npm ci
RUN npm run $BUILD_SCRIPT
